language: ruby
rvm:
 - 2.3.1
before_script:
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec cucumber
after_script:
- bundle exec rake send_to_codeclimate
addons:
  code_climate:
    repo_token: 2ffa1bd1611afa956e99171365919f853c7c501a73662c10f143b2f9f4b76f9b